### ISSUE TITLE
`@pdftron/webviewer` no longer works in `vite-rolldown` version 7.19.0

### ISSUE THREAD

**Issue by chagweyh** [ApryseSDK/webviewer-ui#1105]
Starting from version 7.19.0, `vite-rolldown` changed the way default exports are resolved to make it more consistent with other bundlers, such as esbuild and webpack.

This change breaks `@pdftron/webviewer`. We now see the following error in the console:

```
Uncaught TypeError: WebViewer is not a function
```

Looking at https://cdn.jsdelivr.net/npm/@pdftron/webviewer@11.8.0/public/core/webviewer-core.min.js, both `exports.default` and `__esModule` are used, which may violate this rule: https://publint.dev/rules#cjs_with_esmodule_default_export.

**Additional references:**

- https://esbuild.github.io/content-types/#default-interop
- https://github.com/rolldown/rolldown/issues/6438

**WebViewer version:**
11.8.0

**Reproduction example:**
https://stackblitz.com/~/github.com/chagweyh/webviewer-react

**Comment by bollain** [comment]
Hi @chagweyh,

Thanks for reaching out with this report. Since this involves the WebViewer core can you submit this via our support page? This will help us triage this better. 

We are currently exploring changing to Vite from Webpack so we are investigating some of these issues, your feedback on this is valuable.

https://support.apryse.com/support/tickets/new

**Comment by slapheadted** [comment]
@bollain Are there any updates to report on this? We just upgraded to vite 8.0.0 and hit the same issue as OP.

This is our current workaround:

```
const WebViewer: WebViewerFn = typeof WebViewerModule === "function"
  ? WebViewerModule
  : (WebViewerModule as { default: WebViewerFn }).default;
```

[As per the related Vite docs](https://vite.dev/guide/migration#consistent-commonjs-interop):

> _If you find a package that is affected by this change, please report it to the package author or send them a pull request. Make sure to link to the Rolldown documentation above so that the author can understand the context._

**Comment by DocRog-maker** [comment]
@slapheadted I took your workaround, and extended it slightly as I had problems getting it working. My code ended up as 
```
function normalizeWebViewer(mod: any) {
  if (typeof mod === "function") return mod;
  if (typeof mod?.default === "function") return mod.default;
  if (typeof mod?.WebViewer === "function") return mod.WebViewer;
  if (typeof mod?.default?.WebViewer === "function") return mod.default.WebViewer;
  if (typeof mod?.default?.default === "function") return mod.default.default;
  throw new Error("WebViewer function not found in module");
}

import { useEffect, useRef } from "react";
import * as WebViewerModule from "@pdftron/webviewer";

const WebViewer = normalizeWebViewer(WebViewerModule);

export default function App() {
  const viewerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    WebViewer(
      {
        path: "lib/webviewer", // adjust if needed
        licenseKey: '[Your license key]',
        initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf',
      },
      viewerRef.current!
    );
  }, []);

  return <div className="webviewer" ref={viewerRef} style={{ height: "100vh" }} />;
}
```
